---
# Tasks for gron role

- name: Get latest gron release info
  uri:
    url: "https://api.github.com/repos/tomnomnom/gron/releases/latest"
    method: GET
  register: gron_release_info
  tags:
    - gron

- name: Set gron version and download URL
  set_fact:
    gron_version: "{{ gron_release_info.json.tag_name }}"
    gron_download_url: "https://github.com/tomnomnom/gron/releases/download/{{ gron_release_info.json.tag_name }}/gron-linux-amd64-{{ gron_release_info.json.tag_name | regex_replace('^v', '') }}.tgz"
    gron_filename: "gron-linux-amd64-{{ gron_release_info.json.tag_name | regex_replace('^v', '') }}.tgz"
  tags:
    - gron

- name: Ensure Downloads directory exists
  file:
    path: "/home/{{ ansible_user }}/Downloads"
    state: directory
    mode: '0755'
  tags:
    - gron

- name: Download latest gron tarball
  get_url:
    url: "{{ gron_download_url }}"
    dest: "/home/{{ ansible_user }}/Downloads/{{ gron_filename }}"
    mode: '0644'
  tags:
    - gron

- name: Extract gron tarball
  unarchive:
    src: "/home/{{ ansible_user }}/Downloads/{{ gron_filename }}"
    dest: "/home/{{ ansible_user }}/Downloads"
    remote_src: yes
  tags:
    - gron

- name: Ensure .local/bin directory exists
  file:
    path: "/home/{{ ansible_user }}/.local/bin"
    state: directory
    mode: '0755'
  tags:
    - gron

- name: Install gron to .local/bin
  copy:
    src: "/home/{{ ansible_user }}/Downloads/gron"
    dest: "/home/{{ ansible_user }}/.local/bin/gron"
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    remote_src: yes
  tags:
    - gron

- name: Add gron aliases to bashrc
  lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    line: "{{ item }}"
    create: yes
    backup: yes
  loop:
    - "alias norg='gron --ungron'"
    - "alias ungron='gron --ungron'"
  tags:
    - gron

- name: Clean up downloaded files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/home/{{ ansible_user }}/Downloads/{{ gron_filename }}"
    - "/home/{{ ansible_user }}/Downloads/gron"
  tags:
    - gron
