---
galaxy_info:
  author: your_name
  description: Install GitLab CLI (glab) from latest GitHub releases
  company: your_company
  license: license (GPL-2.0-or-later, MIT, etc)
  min_ansible_version: 2.1
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags: []
dependencies: []