---
# Tasks for micro role

- name: Install clipboard dependencies
  apt:
    name:
      - xclip
      - xsel
      - wl-clipboard
    state: present
  become: yes
  tags:
    - micro

- name: Get latest micro release info
  uri:
    url: "https://api.github.com/repos/zyedidia/micro/releases/latest"
    method: GET
  register: micro_release_info
  tags:
    - micro

- name: Set micro version and download URL
  set_fact:
    micro_version: "{{ micro_release_info.json.tag_name }}"
    micro_download_url: "https://github.com/zyedidia/micro/releases/download/{{ micro_release_info.json.tag_name }}/micro-{{ micro_release_info.json.tag_name | regex_replace('^v', '') }}-linux64.tar.gz"
    micro_filename: "micro-{{ micro_release_info.json.tag_name | regex_replace('^v', '') }}-linux64.tar.gz"
  tags:
    - micro

- name: Ensure Downloads directory exists
  file:
    path: "/home/{{ ansible_user }}/Downloads"
    state: directory
    mode: '0755'
  tags:
    - micro

- name: Download latest micro tarball
  get_url:
    url: "{{ micro_download_url }}"
    dest: "/home/{{ ansible_user }}/Downloads/{{ micro_filename }}"
    mode: '0644'
  tags:
    - micro

- name: Extract micro tarball
  unarchive:
    src: "/home/{{ ansible_user }}/Downloads/{{ micro_filename }}"
    dest: "/home/{{ ansible_user }}/Downloads"
    remote_src: yes
  tags:
    - micro

- name: Ensure .local/bin directory exists
  file:
    path: "/home/{{ ansible_user }}/.local/bin"
    state: directory
    mode: '0755'
  tags:
    - micro

- name: Install micro to .local/bin
  copy:
    src: "/home/{{ ansible_user }}/Downloads/micro-{{ micro_release_info.json.tag_name | regex_replace('^v', '') }}/micro"
    dest: "/home/{{ ansible_user }}/.local/bin/micro"
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    remote_src: yes
  tags:
    - micro

- name: Clean up downloaded files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/home/{{ ansible_user }}/Downloads/{{ micro_filename }}"
    - "/home/{{ ansible_user }}/Downloads/micro-{{ micro_release_info.json.tag_name | regex_replace('^v', '') }}"
  tags:
    - micro
