---
# Tasks for bat role

- name: Get latest bat release info
  uri:
    url: "https://api.github.com/repos/sharkdp/bat/releases/latest"
    method: GET
  register: bat_release_info
  tags:
    - bat

- name: Set bat version and download URL
  set_fact:
    bat_version: "{{ bat_release_info.json.tag_name }}"
    bat_download_url: "https://github.com/sharkdp/bat/releases/download/{{ bat_release_info.json.tag_name }}/bat_{{ bat_release_info.json.tag_name | regex_replace('^v', '') }}_amd64.deb"
    bat_filename: "bat_{{ bat_release_info.json.tag_name | regex_replace('^v', '') }}_amd64.deb"
  tags:
    - bat

- name: Ensure Downloads directory exists
  file:
    path: "/home/{{ ansible_user }}/Downloads"
    state: directory
    mode: '0755'
  tags:
    - bat

- name: Download latest bat .deb package
  get_url:
    url: "{{ bat_download_url }}"
    dest: "/home/{{ ansible_user }}/Downloads/{{ bat_filename }}"
    mode: '0644'
  tags:
    - bat

- name: Install bat package
  apt:
    deb: "/home/{{ ansible_user }}/Downloads/{{ bat_filename }}"
    state: present
  become: yes
  tags:
    - bat

- name: Clean up downloaded .deb file
  file:
    path: "/home/{{ ansible_user }}/Downloads/{{ bat_filename }}"
    state: absent
  tags:
    - bat
