---
galaxy_info:
  author: your_name
  description: Install MinIO Client (mc) from latest releases
  company: your_company
  license: license (GPL-2.0-or-later, MIT, etc)
  min_ansible_version: 2.1
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags: []
dependencies: []